### PR TITLE
Alphabetize genres for enhanced table navigation ✨

### PR DESCRIPTION
**Pull request by Khaleelhabeeb**
This pull request presents a minor but impactful improvement to the HTML table generation: It ensures genres are displayed alphabetically in the first column, except for genre_triggers and genre_christmas which is always prioritized and shown at the top.

### CODE REVIEW

**Comment by skadogg** [comment]
Hi, Khalil. This is a good idea! However, I should have explained my choices in the documentation.

In lines 31 & 32, I randomized the data list (`data_tuples`) and genre list (`all_genres`). This is done so that the final output will be different each time it gets generated.

I think we can still alphabetize the final output while retaining the randomized data: instead of sorting `all_genres` first, we could sort `genre_lists`. This would be right before line 52.

What do you think?

**Comment by Khaleelhabeeb** [comment]
@skadogg , I have tried some solutions  but none works since randomization within each genre is preferred it should be better we leave it untouched.
Attempted Solutions:
Sorting genre_lists at different points.
Randomizing list_with_genre within the loop.
Randomizing genres after sorting.
Implementing a custom sorting function.
Outcome: None of these approaches fully met the requirements without compromising one of the conditions.

**Comment by skadogg** [comment]
It's not the cleanest code, but something like this might work. It follows the same process but sorts the generated `<tr><td>...</td></tr>` strings before writing to the output file.

```
# TV Guide
html_handle.write(modules.html.generate_table_start())
html_handle.write(modules.html.generate_table_th(when_to_start,hours_to_print))

# Write table rows for looped genre_lists, sorted alphabetically
genre_lists_str = []
i = 0
for i in range(len(genre_lists)):
    if genre_lists[i]:
        genre_lists_str.append(str(modules.html.generate_html_genre_tds(genre_lists[i], all_genres[i], hours_to_print)))

genre_lists_str_sorted = sorted(genre_lists_str)

i = 0
for i in range(len(genre_lists_str_sorted)):
    html_handle.write(genre_lists_str_sorted[i])

# Write table rows for keyword lists
if use_keyword_lists:
    html_handle.write(modules.html.generate_html_genre_tds(genre_triggers,'Trigger Warning',hours_to_print))
    html_handle.write(modules.html.generate_html_genre_tds(genre_christmas,'Christmas',hours_to_print))

html_handle.write(modules.html.generate_table_end())
```

**Comment by Khaleelhabeeb** [comment]
yeah this is better something like this will be ok kepping genre_triggers and genre_christmas at the top always                                      
# TV Guide
html_handle.write(modules.html.generate_table_start())
html_handle.write(modules.html.generate_table_th(when_to_start,hours_to_print))

# Write table rows for keyword lists
if use_keyword_lists:
    html_handle.write(modules.html.generate_html_genre_tds(genre_triggers,'Trigger Warning',hours_to_print))
    html_handle.write(modules.html.generate_html_genre_tds(genre_christmas,'Christmas',hours_to_print))

# Write table rows for looped genre_lists, sorted alphabetically
genre_lists_str = []
i = 0
for i in range(len(genre_lists)):
    if genre_lists[i]:
        genre_lists_str.append(str(modules.html.generate_html_genre_tds(genre_lists[i], all_genres[i], hours_to_print)))

genre_lists_str_sorted = sorted(genre_lists_str)

i = 0
for i in range(len(genre_lists_str_sorted)):
    html_handle.write(genre_lists_str_sorted[i])

html_handle.write(modules.html.generate_table_end())

**Pull request merged**
