### PR TITLE
Added try/except to modules > data_bin_convert.py > bin_to_data()

### LINKED ISSUE #94: 🐛 Error when saved_data.bin does not yet exist
We need to test for the existance of saved_data.bin before trying to read from it. If it's not there, show_db should be initialized as an empty list.

```
PS C:\Users\gunner\Documents\git\personal-tv-guide> & c:/Users/gunner/Documents/git/personal-tv-guide/.venv/Scripts/python.exe c:/Users/gunner/Documents/git/personal-tv-guide/run.py

DevTools listening on ws://127.0.0.1:55958/devtools/browser/c7325439-6987-4945-82c9-57fb77f619e0
Signed in successfully
Traceback (most recent call last):
  File "c:\Users\gunner\Documents\git\personal-tv-guide\run.py", line 31, in <module>
    modules.justwatch.scrape_justwatch('TV')
  File "c:\Users\gunner\Documents\git\personal-tv-guide\modules\justwatch.py", line 157, in scrape_justwatch 
    show_db = modules.data_bin_convert.bin_to_data('./my_data/saved_data.bin')
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\gunner\Documents\git\personal-tv-guide\modules\data_bin_convert.py", line 18, in bin_to_data
    fh = open(filename, 'rb')
         ^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: './my_data/saved_data.bin'

```PS C:\Users\gunner\Documents\git\personal-tv-guide>

### PR DESCRIPTION
**Pull request by TechWithVP**
This Fixes #94 

In `modules > data_bin_convert.py > bin_to_data` added try/except.
So if it doesn't find .bin file it will return empty list.

### CODE REVIEW

**Comment by TechWithVP** [comment]
This Fixes #96 

Updated 2 files 
1. classes > activity.py
2. modules > justwatch.py > generate_movies_by_runtime_table

Changes:
- Added condition check for runtime_str if its None return 0
- In generate_movies_by_runtime_table() added condition if duration is 0 return N/A in html table value

**Comment by skadogg** [comment]
This is great, @TechWithVP! I'll take a look and test it out as soon as I can.

**Review by skadogg — CHANGES_REQUESTED** [review]

**Comment by TechWithVP** [comment]
@skadogg I have resolved typo 
`runtime_str = runtime_str = str(data_movies_by_runtime[i].duration) if data_movies_by_runtime[i].duration != 0 else 'N/A'`
to
`runtime_str = str(data_movies_by_runtime[i].duration) if data_movies_by_runtime[i].duration != 0 else 'N/A'`

**Review by skadogg — APPROVED** [review]
Thanks for fixing this, @TechWithVP! I would have just taken care of it for you, but I wasn't sure whether you meant it to be there.

**Pull request merged**
